# Generated by Django 3.1.7 on 2021-03-27 03:19

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('difficulty', models.CharField(choices=[('Easy', 'EASY'), ('Medium', 'MEDIUM'), ('Hard', 'HARD')], default='Easy', max_length=10)),
                ('companyTags', models.TextField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('question_id', models.IntegerField()),
                ('Wishlisted_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('link', models.URLField()),
                ('difficulty', models.CharField(choices=[('Easy', 'EASY'), ('Medium', 'MEDIUM'), ('Hard', 'HARD')], default='Easy', max_length=10)),
                ('companyTags', models.TextField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('timetaken', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'topquestion',
                'verbose_name_plural': 'topquestions',
                'ordering': ('question_name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
