# Generated by Django 3.1.7 on 2021-03-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackBitApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/company/'),
            preserve_default=False,
        ),
    ]
