# Generated by Django 3.1.7 on 2021-03-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackBitApp', '0002_company_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('photo1', models.ImageField(upload_to='photos/company/roadmap')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/company/roadmap')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/company/roadmap')),
            ],
            options={
                'verbose_name': 'roadmap',
                'verbose_name_plural': 'roadmaps',
                'ordering': ('company_name',),
            },
        ),
    ]
