# Generated by Django 3.1.7 on 2021-03-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackBitApp', '0003_roadmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=200, unique=True)),
                ('answers', models.TextField(max_length=1000)),
            ],
        ),
    ]
